# Configuration du projet

### Clônage du dépôt

In [ ]:
!git clone https://github.com/wydad-fulbert/NegativePrompt.git
%cd NegativePrompt

Cloning into 'NegativePrompt'...
remote: Enumerating objects: 446, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 446 (delta 53), reused 60 (delta 21), pack-reused 353 (from 1)
Receiving objects: 100% (446/446), 4.91 MiB | 12.80 MiB/s, done.
Resolving deltas: 100% (212/212), done.
/kaggle/working/NegativePrompt/NegativePrompt/NegativePrompt

### Installation des dépendances

In [ ]:
!pip install -r requirements.txt

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.13.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (4.67.3)
Collecting fire (from -r requirements.txt (line 6))
  Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 2)) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->-r requirements.txt (line 3)) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate->-r requirements.txt (line 3)) (2.10.0+cu128)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from fire->-r requirements.txt (line 6)) (3.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 2)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 2)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 2)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 2)) (2026.2.25)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r requirements.txt (line 2)) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 2)) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate->-r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 1)) (0.1.2)
Downloading fire-0.7.1-py3-none-any.whl (115 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 kB 4.7 MB/s eta 0:00:00
Installing collected packages: fire
Successfully installed fire-0.7.1

In [ ]:
!pip install -U transformers accelerate bitsandbytes sentencepiece
!pip install fire
!pip install nltk

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 111.8 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 42.5 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bitsandbytes-0.49.2 transformers-5.3.0
Requirement already satisfied: fire in /usr/local/lib/python3.12/dist-packages (0.7.1)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from fire) (3.3.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import pandas as pd

### Vérification du GPU

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

# **PARTIE I — Reproduction solide des baselines**

### PROTOCOLE

**1. Modèles**

 * Flan-T5-Large

 * Llama-2-7B-Chat

 * Vicuna-7B-v1.5

**2. Tâches**


* *Instruction Induction (5)* :
   - sentiment

   - translation_en-fr

   - word_in_context

   - active_to_passive

   - negation


* *BigBench (5)* :

  - dyck_languages

  - object_counting

  - ruin_names

  - word_sorting

  - disambiguation_qa

**3. Stimuli**




* 0 (baseline)
  ,1, 5, et 10


Stimulus 0 correspond à la baseline (sans Negative Prompt).
Stimulus 1, 5 et 10 correspondent respectivement aux prompts NP01, NP05 et NP10.





**4. Paramètres**

  * Zero-shot (few_shot=False)

  * Température = 0

  * max_new_tokens = 50

  * num_samples = 100

  * seed = 42

### Modèle Flan-T5-Large

In [ ]:
!python run_t5.py

In [ ]:
import pandas as pd
dt5 = pd.read_csv("results_t5.csv")
dt5.head(10)

### Modèle Llama-2-7B-Chat

In [ ]:
### Accès à HuggingFace
from google.colab import userdata
import os

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

In [ ]:
!python run_llama2.py

In [ ]:
dllama = pd.read_csv("/content/NegativePrompt/NegativePrompt/RESULTS/results_10_tasks/results_llama2.csv")
dllama.head(10)

### Modèle Vicuna-7B-v1.5

In [ ]:
! python run_vicuna.py

In [ ]:
import pandas as pd
dvicuna = pd.read_csv("/content/NegativePrompt/NegativePrompt/RESULTS/results_10_tasks/results_vicuna.csv")
dvicuna.head(5)

## **Analyse des résultats**

In [ ]:
# Fusion des 3 fichiers résultats
import pandas as pd
t5 = pd.read_csv("/content/NegativePrompt/NegativePrompt/RESULTS/results_10_tasks/results_t5.csv")
llama = pd.read_csv("/content/NegativePrompt/NegativePrompt/RESULTS/results_10_tasks/results_llama2.csv")
vicuna = pd.read_csv("/content/NegativePrompt/NegativePrompt/RESULTS/results_10_tasks/results_vicuna.csv")
df = pd.concat([t5, llama, vicuna])

### Performance moyenne globale par modèle

In [ ]:
df.groupby("model")["score"].mean()

La figure présente la performance moyenne des trois modèles sur l’ensemble des tâches.

On observe que **Llama2** obtient les meilleurs résultats globaux (≈0.35), suivi de **Vicuna** (≈0.26), tandis que **Flan-T5** présente les performances les plus faibles (≈0.22).

Cependant, cette moyenne globale peut masquer des différences importantes selon les tâches, ce qui motive l’analyse détaillée présentée dans la section suivante.

In [ ]:
sns.barplot(
    data=df,
    x="model",
    y="score"
)

plt.title("Performance moyenne par modèle")
plt.show()

### Analyse par tâche

In [ ]:
df.groupby(["task","model"])["score"].mean().round(2).unstack()

In [ ]:
sns.barplot(
    data=df,
    x="task",
    y="score",
    hue="model"
)

plt.xticks(rotation=45)
plt.title("Performance par tâche et par modèle")
plt.show()

In [ ]:
plt.figure(figsize=(12,5))

sns.barplot(
    data=df,
    x="task",
    y="score",
    hue="model",
    errorbar=None
)

plt.xticks(rotation=30, ha="right")
plt.title("Performance par tâche et par modèle")
plt.ylabel("Score")
plt.xlabel("Tâche")

plt.tight_layout()
plt.show()

L'analyse par tâche révèle des variations importantes entre les modèles.

Par exemple :

- **active_to_passive** est presque parfaitement résolue par Llama2 (**0.97**) alors que T5 échoue presque complètement (**0.02**).
- **sentiment** est mieux traité par T5 (**0.93**) que par les autres modèles.
- **object_counting** est légèrement mieux résolu par Vicuna (**0.26**).

Certaines tâches comme **ruin_names** ou **word_sorting** restent très difficiles pour tous les modèles (scores proches de 0).

### Effets des Negative Prompts

In [ ]:
df.groupby(["stimulus","model"])["score"].mean().round(2).unstack()

In [ ]:
sns.barplot(
    data=df,
    x="stimulus",
    y="score",
    hue="model"
)

On observe que les performances de **T5 restent quasiment constantes** (≈0.21–0.22) quel que soit le stimulus.

Cela suggère que les Negative Prompts ont **peu d'effet sur ce modèle**, contrairement à Llama2 et Vicuna qui montrent des variations plus importantes selon le stimulus.

Ce résultat confirme l'observation mentionnée dans le papier : certains modèles semblent plus sensibles aux modifications du prompt que d'autres.

## **Limites de la métrique Exact Match (EM) et métrique alternative**

La métrique Exact Match (EM) est très stricte pour certaines tâches génératives, comme la traduction. Deux réponses proches peuvent être considérées comme incorrectes si elles ne sont pas exactement identiques.

Pour illustrer cette limite, nous calculons également une mesure de similarité textuelle : le score **BLEU**, qui compare la réponse générée par le modèle à la réponse de référence.

In [ ]:
# Script sur les 3 modèles , 3 tâches , incluant  la métrique BLEU
!python run_3models_bleu.py

Afin d’illustrer concrètement le comportement des modèles, nous affichons quelques exemples de prédictions pour trois tâches génératives.

Pour chaque tâche et chaque modèle, nous montrons un exemple avec la condition **baseline (stimulus = 0)** et un exemple avec **Negative Prompt (stimulus = 5)**.

Le tableau présente l’entrée (input), la réponse attendue (reference), la prédiction du modèle (prediction), ainsi que les scores Exact Match et BLEU.

In [ ]:
import pandas as pd
bleu_df = pd.read_csv("/content/NegativePrompt/RESULTS/results_10_tasks/results_bleu_3models_detailed.csv")
tasks_to_show = ["translation_en-fr", "active_to_passive", "ruin_names"]
stimuli_to_show = [0, 5]

examples = (
    bleu_df[
        (bleu_df["task"].isin(tasks_to_show)) &
        (bleu_df["stimulus"].isin(stimuli_to_show))
    ]
    .groupby(["model","task","stimulus"])
    .head(1)
    [["model","task","stimulus","input","reference","prediction","em_normalized","bleu"]]
)
examples = examples.sort_values(["task","model","stimulus"])
examples

In [ ]:
bleu_df.groupby(["model","task","stimulus"])[["em_normalized","bleu"]].mean().round(2)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

bleu_summary = bleu_df.groupby(["model","task"])[["em_normalized","bleu"]].mean().reset_index()

plt.figure(figsize=(8,4))

sns.barplot(
    data=bleu_summary,
    x="task",
    y="bleu",
    hue="model"
)

plt.title("Score BLEU par tâche et par modèle")
plt.xticks(rotation=30)
plt.show()

#### Comparaison entre Exact Match (EM) et BLEU

Les résultats montrent que les scores BLEU sont généralement plus élevés que les scores Exact Match pour certaines tâches génératives.

Par exemple, pour la tâche **active_to_passive**, les modèles obtiennent des scores BLEU élevés même lorsque le score Exact Match est plus faible. Cela signifie que les réponses générées sont souvent proches de la référence, même si elles ne sont pas identiques.

Pour la tâche **translation_en-fr**, on observe également que les scores BLEU capturent une certaine similarité entre la prédiction et la référence, alors que Exact Match reste souvent nul.

Ces résultats illustrent la limite de la métrique Exact Match : elle peut sous-estimer la qualité des réponses générées lorsque plusieurs formulations correctes sont possibles.

# **PARTIE II — Ablations : contrôles de longueur et de saillance**

Nous comparons quatre conditions :

- **baseline** : prompt original sans Negative Prompt  
- **np01** : ajout du Negative Prompt NP01  
- **neutral_salience** : ajout d’un marqueur saillant mais neutre ("IMPORTANT:")  
- **neutral_length** : ajout d’un texte neutre de longueur comparable  

Ces contrôles permettent de vérifier si l’effet observé avec les Negative Prompts provient réellement de leur contenu, ou plus généralement du fait d’ajouter un texte supplémentaire au prompt.

Nous analysons ensuite si les performances obtenues avec les contrôles neutres sont proches de celles obtenues avec NP01.

In [ ]:
### Accès à HuggingFace
from google.colab import userdata
import os

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

Les expériences d’ablation sont en cours d’exécution au moment de l’envoi de ce notebook. Les résultats présentés ici concernent principalement les modèles T5 et Llama2, tandis que l’exécution pour Vicuna n’est pas encore terminée en raison des contraintes de calcul. L’analyse ci-dessous doit donc être interprétée comme une analyse préliminaire.

In [ ]:
#expériences d’ablation sur 3 modèles et 5 tâches, en comparant : baseline,Negative Prompt NP01, deux contrôles neutres de longueur et de saillance.
!python run_control.py

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

controls = pd.read_csv("results_controls_all_models.csv")
controls.head()

Pour le modèle T5, les résultats montrent des écarts très faibles entre les différentes conditions. Les différences entre baseline, NP01 et les contrôles neutres restent généralement inférieures à 0.03 selon les tâches.

Cela suggère que T5 est globalement peu sensible aux modifications du prompt dans notre protocole expérimental, ce qui confirme également l’observation faite dans l’analyse précédente sur la stabilité de ce modèle face aux Negative Prompts.

In [ ]:
controls.groupby(["model", "task", "condition"]).size().reset_index(name="n")

Pour Llama2, les résultats sont plus variables selon les tâches. Dans certains cas, NP01 apporte une légère amélioration (par exemple +0.02 sur translation_en-fr), tandis que dans d’autres cas les contrôles neutres produisent des effets comparables voire supérieurs (par exemple +0.08 pour neutral_salience sur object_counting).

Ces résultats suggèrent que l’effet du Negative Prompt n’est pas systématiquement lié à son contenu, et qu’une partie de l’effet pourrait être expliquée par des facteurs plus généraux comme la saillance ou la longueur du texte ajouté.

In [ ]:
pivot_diff = controls.pivot_table(
    index=["model", "task"],
    columns="condition",
    values="score"
)

pivot_diff["np01_minus_baseline"] = pivot_diff["np01"] - pivot_diff["baseline"]
pivot_diff["neutral_length_minus_baseline"] = pivot_diff["neutral_length"] - pivot_diff["baseline"]
pivot_diff["neutral_salience_minus_baseline"] = pivot_diff["neutral_salience"] - pivot_diff["baseline"]

pivot_diff[[
    "np01_minus_baseline",
    "neutral_length_minus_baseline",
    "neutral_salience_minus_baseline"
]].round(3)

In [ ]:
diff_summary = pivot_diff[[
    "np01_minus_baseline",
    "neutral_length_minus_baseline",
    "neutral_salience_minus_baseline"
]].mean().round(3)

diff_summary

L’objectif de ces expériences est de déterminer si l’effet observé avec les Negative Prompts provient réellement de leur contenu, ou simplement du fait d’ajouter du texte supplémentaire au prompt.

Pour cela, nous comparons quatre conditions : baseline, NP01, neutral_salience (marqueur neutre) et neutral_length (texte neutre de longueur comparable).

Dans l’ensemble, les résultats préliminaires indiquent que les Negative Prompts n’apportent pas d’amélioration systématique des performances. Les écarts observés restent faibles et parfois comparables à ceux obtenus avec des contrôles neutres.

Ces observations vont dans le sens d’une interprétation prudente de l’effet des Negative Prompts, qui pourrait en partie s’expliquer par des facteurs liés à la structure du prompt plutôt qu’au contenu sémantique lui-même.

Une analyse complète sera réalisée une fois l’ensemble des modèles exécuté.

# **Partie III : Améliorations**

### Test 1 NP auto generated

In [ ]:
!python run_np_auto.py

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

npauto = pd.read_csv("results_np_auto.csv")
npauto.head()

In [ ]:
npauto.head()

In [ ]:
npauto.groupby(["model","condition"])["score"].mean().unstack().round(3)

In [ ]:
npauto.pivot_table(
    index=["model","task"],
    columns="condition",
    values="score"
).round(2)

In [ ]:
!python run_np_auto_llama2.py

### Test finetuning LoRa

In [ ]:
!python build_lora_dataset.py

In [ ]:
###UNIQUEMENT SUR KAGGLE (ACCES A HUGGING FACE)

from kaggle_secrets import UserSecretsClient
from huggingface_hub import login
import os

user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")

os.environ["HF_TOKEN"] = hf_token
login(token=hf_token)
print("HF OK")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

HF OK

In [ ]:
!pip install -q transformers datasets peft accelerate sentencepiece evaluate sacrebleu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 5.0 MB/s eta 0:00:00

In [ ]:
!python train_t5_lora.py

Generating train split: 56688 examples [00:00, 402523.67 examples/s]
config.json: 100%|█████████████████████████████| 662/662 [00:00<00:00, 2.00MB/s]
tokenizer_config.json: 2.54kB [00:00, 930kB/s]
spiece.model: 100%|██████████████████████████| 792k/792k [00:00<00:00, 2.52MB/s]
tokenizer.json: 2.42MB [00:00, 19.3MB/s]
special_tokens_map.json: 2.20kB [00:00, 6.09MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors: 100%|████████████████████| 3.13G/3.13G [00:07<00:00, 433MB/s]
Loading weights: 100%|███████████████████████| 558/558 [00:00<00:00, 796.90it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
generation_config.json: 100%|███████████████████| 147/147 [00:00<00:00, 709kB/s]
trainable params: 2,359,296 || all params: 785,509,376 || trainable%: 0.3004
Map: 100%|███████████████████████| 56688/56688 [00:08<00:00, 7074.43 examples/s]
  0%|                                                  | 0/3543 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
{'loss': '45.23', 'grad_norm': 'nan', 'learning_rate': '9.862e-05', 'epoch': '0.01411'}
{'loss': '46.33', 'grad_norm': 'nan', 'learning_rate': '9.721e-05', 'epoch': '0.02822'}
{'loss': '44', 'grad_norm': 'nan', 'learning_rate': '9.579e-05', 'epoch': '0.04234'}
{'loss': '127.9', 'grad_norm': 'nan', 'learning_rate': '9.438e-05', 'epoch': '0.05645'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '9.297e-05', 'epoch': '0.07056'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '9.156e-05', 'epoch': '0.08467'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '9.015e-05', 'epoch': '0.09879'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.874e-05', 'epoch': '0.1129'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.733e-05', 'epoch': '0.127'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.592e-05', 'epoch': '0.1411'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.45e-05', 'epoch': '0.1552'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.309e-05', 'epoch': '0.1693'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.168e-05', 'epoch': '0.1835'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.027e-05', 'epoch': '0.1976'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.886e-05', 'epoch': '0.2117'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.745e-05', 'epoch': '0.2258'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.604e-05', 'epoch': '0.2399'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.463e-05', 'epoch': '0.254'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.321e-05', 'epoch': '0.2681'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.18e-05', 'epoch': '0.2822'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.039e-05', 'epoch': '0.2964'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.898e-05', 'epoch': '0.3105'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.757e-05', 'epoch': '0.3246'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.616e-05', 'epoch': '0.3387'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.475e-05', 'epoch': '0.3528'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.334e-05', 'epoch': '0.3669'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.192e-05', 'epoch': '0.381'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.051e-05', 'epoch': '0.3951'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.91e-05', 'epoch': '0.4093'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.769e-05', 'epoch': '0.4234'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.628e-05', 'epoch': '0.4375'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.487e-05', 'epoch': '0.4516'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.346e-05', 'epoch': '0.4657'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.205e-05', 'epoch': '0.4798'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.064e-05', 'epoch': '0.4939'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.922e-05', 'epoch': '0.508'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.781e-05', 'epoch': '0.5222'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.64e-05', 'epoch': '0.5363'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.499e-05', 'epoch': '0.5504'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.358e-05', 'epoch': '0.5645'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.217e-05', 'epoch': '0.5786'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.076e-05', 'epoch': '0.5927'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.935e-05', 'epoch': '0.6068'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.793e-05', 'epoch': '0.6209'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.652e-05', 'epoch': '0.6351'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.511e-05', 'epoch': '0.6492'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.37e-05', 'epoch': '0.6633'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.229e-05', 'epoch': '0.6774'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '3.088e-05', 'epoch': '0.6915'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.947e-05', 'epoch': '0.7056'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.806e-05', 'epoch': '0.7197'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.664e-05', 'epoch': '0.7338'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.523e-05', 'epoch': '0.748'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.382e-05', 'epoch': '0.7621'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.241e-05', 'epoch': '0.7762'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.1e-05', 'epoch': '0.7903'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.959e-05', 'epoch': '0.8044'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.818e-05', 'epoch': '0.8185'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.677e-05', 'epoch': '0.8326'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.535e-05', 'epoch': '0.8467'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.394e-05', 'epoch': '0.8609'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.253e-05', 'epoch': '0.875'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.112e-05', 'epoch': '0.8891'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '9.709e-06', 'epoch': '0.9032'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '8.298e-06', 'epoch': '0.9173'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '6.887e-06', 'epoch': '0.9314'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.476e-06', 'epoch': '0.9455'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '4.064e-06', 'epoch': '0.9596'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '2.653e-06', 'epoch': '0.9738'}
{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '1.242e-06', 'epoch': '0.9879'}
{'train_runtime': '2.457e+04', 'train_samples_per_second': '2.307', 'train_steps_per_second': '0.144', 'train_loss': '3.719', 'epoch': '1'}
100%|█████████████████████████████████████| 3543/3543 [6:49:34<00:00,  6.94s/it]
LoRA training finished.

##### Vérification du modèle (absence de vide, d'absurdité...)

In [ ]:
!python debug_t5_lora.py

`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 558/558 [00:00<00:00, 910.22it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Loading weights: 100%|███████████████████████| 558/558 [00:00<00:00, 939.24it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

PROMPT: Instruction: Determine whether a movie review is positive or negative.

Input: This film was excellent and moving.
Answer:
BASE: positive
LORA:

PROMPT: Instruction: Translate the word into French.

Input: hello
Answer:
BASE: Hello
LORA:

PROMPT: Instruction: Count the number of objects described in the input.

Input: I have 3 apples and 2 bananas.
Answer:
BASE: 4
LORA:

##### Evaluation

In [ ]:
!python eval_t5_lora.py

`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 558/558 [00:00<00:00, 948.41it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Loading weights: 100%|███████████████████████| 558/558 [00:00<00:00, 963.68it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

=== CONDITION: baseline ===

=== CONDITION: np01 ===

=== CONDITION: np05 ===

=== CONDITION: np10 ===
                 task condition    metric_used  score_base  score_lora
0   active_to_passive  baseline           bleu    0.143427    0.000000
1   active_to_passive      np01           bleu    0.113890    0.000000
2   active_to_passive      np05           bleu    0.113113    0.000000
3   active_to_passive      np10           bleu    0.111653    0.000000
4   disambiguation_qa  baseline  normalized_em    0.000000    0.000000
5   disambiguation_qa      np01  normalized_em    0.000000    0.000000
6   disambiguation_qa      np05  normalized_em    0.000000    0.000000
7   disambiguation_qa      np10  normalized_em    0.000000    0.000000
8      dyck_languages  baseline  normalized_em    0.533333    0.266667
9      dyck_languages      np01  normalized_em    0.466667    0.266667
10     dyck_languages      np05  normalized_em    0.566667    0.266667
11     dyck_languages      np10  normalized_em    0.500000    0.266667
12           negation  baseline  normalized_em    0.000000    0.000000
13           negation      np01  normalized_em    0.000000    0.000000
14           negation      np05  normalized_em    0.000000    0.000000
15           negation      np10  normalized_em    0.000000    0.000000
16    object_counting  baseline  normalized_em    0.266667    0.000000
17    object_counting      np01  normalized_em    0.266667    0.000000
18    object_counting      np05  normalized_em    0.266667    0.000000
19    object_counting      np10  normalized_em    0.300000    0.000000
20         ruin_names  baseline           bleu    0.194216    0.000000
21         ruin_names      np01           bleu    0.202629    0.000000
22         ruin_names      np05           bleu    0.183878    0.000000
23         ruin_names      np10           bleu    0.178894    0.000000
24          sentiment  baseline  normalized_em    0.900000    0.000000
25          sentiment      np01  normalized_em    0.900000    0.000000
26          sentiment      np05  normalized_em    0.900000    0.000000
27          sentiment      np10  normalized_em    0.900000    0.000000
28  translation_en-fr  baseline           bleu    0.082986    0.000000
29  translation_en-fr      np01           bleu    0.087028    0.000000
30  translation_en-fr      np05           bleu    0.075173    0.000000
31  translation_en-fr      np10           bleu    0.076116    0.000000
32    word_in_context  baseline  normalized_em    0.566667    0.000000
33    word_in_context      np01  normalized_em    0.566667    0.000000
34    word_in_context      np05  normalized_em    0.500000    0.000000
35    word_in_context      np10  normalized_em    0.566667    0.000000
36       word_sorting  baseline  normalized_em    0.000000    0.000000
37       word_sorting      np01  normalized_em    0.000000    0.000000
38       word_sorting      np05  normalized_em    0.000000    0.000000
39       word_sorting      np10  normalized_em    0.000000    0.000000

Saved to: /kaggle/working/results_t5_lora_eval_fixed.csv

In [ ]:
from google.colab import files
files.upload()

Saving results_t5_lora_eval_fixed.csv to results_t5_lora_eval_fixed.csv

{'results_t5_lora_eval_fixed.csv': b'task,condition,metric_used,score_base,score_lora\nactive_to_passive,baseline,bleu,0.1434273302541761,0.0\nactive_to_passive,np01,bleu,0.11389034164225112,0.0\nactive_to_passive,np05,bleu,0.11311311875408814,0.0\nactive_to_passive,np10,bleu,0.11165325332949196,0.0\ndisambiguation_qa,baseline,normalized_em,0.0,0.0\ndisambiguation_qa,np01,normalized_em,0.0,0.0\ndisambiguation_qa,np05,normalized_em,0.0,0.0\ndisambiguation_qa,np10,normalized_em,0.0,0.0\ndyck_languages,baseline,normalized_em,0.5333333333333333,0.26666666666666666\ndyck_languages,np01,normalized_em,0.4666666666666667,0.26666666666666666\ndyck_languages,np05,normalized_em,0.5666666666666667,0.26666666666666666\ndyck_languages,np10,normalized_em,0.5,0.26666666666666666\nnegation,baseline,normalized_em,0.0,0.0\nnegation,np01,normalized_em,0.0,0.0\nnegation,np05,normalized_em,0.0,0.0\nnegation,np10,normalized_em,0.0,0.0\nobject_counting,baseline,normalized_em,0.26666666666666666,0.0\nobject_counting,np01,normalized_em,0.26666666666666666,0.0\nobject_counting,np05,normalized_em,0.26666666666666666,0.0\nobject_counting,np10,normalized_em,0.3,0.0\nruin_names,baseline,bleu,0.1942160942772221,0.0\nruin_names,np01,bleu,0.2026287043327793,0.0\nruin_names,np05,bleu,0.18387801311242447,0.0\nruin_names,np10,bleu,0.17889351717502042,0.0\nsentiment,baseline,normalized_em,0.9,0.0\nsentiment,np01,normalized_em,0.9,0.0\nsentiment,np05,normalized_em,0.9,0.0\nsentiment,np10,normalized_em,0.9,0.0\ntranslation_en-fr,baseline,bleu,0.08298637246848307,0.0\ntranslation_en-fr,np01,bleu,0.08702776630982814,0.0\ntranslation_en-fr,np05,bleu,0.07517257024290198,0.0\ntranslation_en-fr,np10,bleu,0.07611567233896098,0.0\nword_in_context,baseline,normalized_em,0.5666666666666667,0.0\nword_in_context,np01,normalized_em,0.5666666666666667,0.0\nword_in_context,np05,normalized_em,0.5,0.0\nword_in_context,np10,normalized_em,0.5666666666666667,0.0\nword_sorting,baseline,normalized_em,0.0,0.0\nword_sorting,np01,normalized_em,0.0,0.0\nword_sorting,np05,normalized_em,0.0,0.0\nword_sorting,np10,normalized_em,0.0,0.0\n'}

In [ ]:
import pandas as pd
df_lora = pd.read_csv("results_t5_lora_eval_fixed.csv")
df_lora["gain"] = df_lora["score_lora"] - df_lora["score_base"]
df_lora[["task","condition","metric_used","score_base","score_lora","gain"]].round(4)

                 task condition    metric_used  score_base  score_lora    gain
0   active_to_passive  baseline           bleu      0.1434      0.0000 -0.1434
1   active_to_passive      np01           bleu      0.1139      0.0000 -0.1139
2   active_to_passive      np05           bleu      0.1131      0.0000 -0.1131
3   active_to_passive      np10           bleu      0.1117      0.0000 -0.1117
4   disambiguation_qa  baseline  normalized_em      0.0000      0.0000  0.0000
5   disambiguation_qa      np01  normalized_em      0.0000      0.0000  0.0000
6   disambiguation_qa      np05  normalized_em      0.0000      0.0000  0.0000
7   disambiguation_qa      np10  normalized_em      0.0000      0.0000  0.0000
8      dyck_languages  baseline  normalized_em      0.5333      0.2667 -0.2667
9      dyck_languages      np01  normalized_em      0.4667      0.2667 -0.2000
10     dyck_languages      np05  normalized_em      0.5667      0.2667 -0.3000
11     dyck_languages      np10  normalized_em      0.5000      0.2667 -0.2333
12           negation  baseline  normalized_em      0.0000      0.0000  0.0000
13           negation      np01  normalized_em      0.0000      0.0000  0.0000
14           negation      np05  normalized_em      0.0000      0.0000  0.0000
15           negation      np10  normalized_em      0.0000      0.0000  0.0000
16    object_counting  baseline  normalized_em      0.2667      0.0000 -0.2667
17    object_counting      np01  normalized_em      0.2667      0.0000 -0.2667
18    object_counting      np05  normalized_em      0.2667      0.0000 -0.2667
19    object_counting      np10  normalized_em      0.3000      0.0000 -0.3000
20         ruin_names  baseline           bleu      0.1942      0.0000 -0.1942
21         ruin_names      np01           bleu      0.2026      0.0000 -0.2026
22         ruin_names      np05           bleu      0.1839      0.0000 -0.1839
23         ruin_names      np10           bleu      0.1789      0.0000 -0.1789
24          sentiment  baseline  normalized_em      0.9000      0.0000 -0.9000
25          sentiment      np01  normalized_em      0.9000      0.0000 -0.9000
26          sentiment      np05  normalized_em      0.9000      0.0000 -0.9000
27          sentiment      np10  normalized_em      0.9000      0.0000 -0.9000
28  translation_en-fr  baseline           bleu      0.0830      0.0000 -0.0830
29  translation_en-fr      np01           bleu      0.0870      0.0000 -0.0870
30  translation_en-fr      np05           bleu      0.0752      0.0000 -0.0752
31  translation_en-fr      np10           bleu      0.0761      0.0000 -0.0761
32    word_in_context  baseline  normalized_em      0.5667      0.0000 -0.5667
33    word_in_context      np01  normalized_em      0.5667      0.0000 -0.5667
34    word_in_context      np05  normalized_em      0.5000      0.0000 -0.5000
35    word_in_context      np10  normalized_em      0.5667      0.0000 -0.5667
36       word_sorting  baseline  normalized_em      0.0000      0.0000  0.0000
37       word_sorting      np01  normalized_em      0.0000      0.0000  0.0000
38       word_sorting      np05  normalized_em      0.0000      0.0000  0.0000
39       word_sorting      np10  normalized_em      0.0000      0.0000  0.0000

### Test n°2 amélioaration NP auto generated

In [ ]:
## Installation des dépendances
! pip install transformers datasets nltk -q

##### Test sur Flan-T5-Large

In [ ]:
!python eval_final_np_t5.py

config.json: 100%|█████████████████████████████| 662/662 [00:00<00:00, 2.15MB/s]
tokenizer_config.json: 2.54kB [00:00, 6.45MB/s]
spiece.model: 100%|██████████████████████████| 792k/792k [00:00<00:00, 1.76MB/s]
tokenizer.json: 2.42MB [00:00, 54.9MB/s]
special_tokens_map.json: 2.20kB [00:00, 6.73MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors: 100%|████████████████████| 3.13G/3.13G [00:07<00:00, 429MB/s]
Loading weights: 100%|█| 558/558 [00:00<00:00, 609.49it/s, Materializing param=s
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
generation_config.json: 100%|███████████████████| 147/147 [00:00<00:00, 527kB/s]

=== baseline ===

=== np01 ===

=== np05 ===

=== np10 ===

=== np_generated ===
                 task     condition metric     score
0   active_to_passive      baseline   bleu  0.143427
1   active_to_passive          np01   bleu  0.113890
2   active_to_passive          np05   bleu  0.113113
3   active_to_passive          np10   bleu  0.111653
4   active_to_passive  np_generated   bleu  0.172964
5   disambiguation_qa      baseline     em  0.000000
6   disambiguation_qa          np01     em  0.000000
7   disambiguation_qa          np05     em  0.000000
8   disambiguation_qa          np10     em  0.000000
9   disambiguation_qa  np_generated     em  0.066667
10     dyck_languages      baseline     em  0.533333
11     dyck_languages          np01     em  0.466667
12     dyck_languages          np05     em  0.566667
13     dyck_languages          np10     em  0.500000
14     dyck_languages  np_generated     em  0.533333
15           negation      baseline     em  0.000000
16           negation          np01     em  0.000000
17           negation          np05     em  0.000000
18           negation          np10     em  0.000000
19           negation  np_generated     em  0.000000
20    object_counting      baseline     em  0.266667
21    object_counting          np01     em  0.266667
22    object_counting          np05     em  0.266667
23    object_counting          np10     em  0.300000
24    object_counting  np_generated     em  0.300000
25         ruin_names      baseline   bleu  0.194216
26         ruin_names          np01   bleu  0.202629
27         ruin_names          np05   bleu  0.183878
28         ruin_names          np10   bleu  0.178894
29         ruin_names  np_generated   bleu  0.205043
30          sentiment      baseline     em  0.900000
31          sentiment          np01     em  0.900000
32          sentiment          np05     em  0.900000
33          sentiment          np10     em  0.900000
34          sentiment  np_generated     em  0.900000
35  translation_en-fr      baseline   bleu  0.082986
36  translation_en-fr          np01   bleu  0.087028
37  translation_en-fr          np05   bleu  0.075173
38  translation_en-fr          np10   bleu  0.076116
39  translation_en-fr  np_generated   bleu  0.082043
40    word_in_context      baseline     em  0.000000
41    word_in_context          np01     em  0.000000
42    word_in_context          np05     em  0.000000
43    word_in_context          np10     em  0.000000
44    word_in_context  np_generated     em  0.000000
45       word_sorting      baseline     em  0.000000
46       word_sorting          np01     em  0.000000
47       word_sorting          np05     em  0.000000
48       word_sorting          np10     em  0.000000
49       word_sorting  np_generated     em  0.000000

Saved to: results_final_np_t5.csv

In [ ]:
import os

filename = "results_final_np.csv"  # Remplacez par le nom exact de votre fichier
for root, dirs, files in os.walk('/content'):
    if filename in files:
        print(os.path.join(root, filename))

/content/NegativePrompt/NegativePrompt/NegativePrompt/results_final_np.csv
/content/NegativePrompt/NegativePrompt/NegativePrompt/NegativePrompt/results_final_np.csv

In [ ]:
import pandas as pd

# Ajoutez des guillemets autour du chemin
df = pd.read_csv("/kaggle/working/NegativePrompt/NegativePrompt/results_final_np_t5.csv")

# Pour vérifier que le chargement a fonctionné
df.head(20)

                 task     condition metric     score
0   active_to_passive      baseline   bleu  0.143427
1   active_to_passive          np01   bleu  0.113890
2   active_to_passive          np05   bleu  0.113113
3   active_to_passive          np10   bleu  0.111653
4   active_to_passive  np_generated   bleu  0.172964
5   disambiguation_qa      baseline     em  0.000000
6   disambiguation_qa          np01     em  0.000000
7   disambiguation_qa          np05     em  0.000000
8   disambiguation_qa          np10     em  0.000000
9   disambiguation_qa  np_generated     em  0.066667
10     dyck_languages      baseline     em  0.533333
11     dyck_languages          np01     em  0.466667
12     dyck_languages          np05     em  0.566667
13     dyck_languages          np10     em  0.500000
14     dyck_languages  np_generated     em  0.533333
15           negation      baseline     em  0.000000
16           negation          np01     em  0.000000
17           negation          np05     em  0.000000
18           negation          np10     em  0.000000
19           negation  np_generated     em  0.000000

##### Test sur Llama-2-7B-Chat

In [ ]:
#### UNIQUEMENT POUR COLAB
### Accès à HuggingFace
from google.colab import userdata
import os

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

TimeoutException: Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.

In [ ]:
!python eval_final_np_llama2.py

config.json: 100%|█████████████████████████████| 614/614 [00:00<00:00, 2.65MB/s]
tokenizer_config.json: 1.62kB [00:00, 4.32MB/s]
tokenizer.json: 1.84MB [00:00, 41.6MB/s]
tokenizer.model: 100%|███████████████████████| 500k/500k [00:00<00:00, 2.04MB/s]
special_tokens_map.json: 100%|█████████████████| 414/414 [00:00<00:00, 2.41MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors.index.json: 26.8kB [00:00, 60.1MB/s]
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Downloading (incomplete total...): 100%|████| 13.5G/13.5G [00:39<00:00, 506MB/s]
Fetching 2 files: 100%|███████████████████████████| 2/2 [00:39<00:00, 19.62s/it]
Download complete: 100%|████████████████████| 13.5G/13.5G [00:39<00:00, 342MB/s]
Loading weights: 100%|█| 291/291 [00:03<00:00, 78.03it/s, Materializing param=mo
generation_config.json: 100%|██████████████████| 188/188 [00:00<00:00, 1.13MB/s]

=== baseline ===
The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

=== np01 ===

=== np05 ===

=== np10 ===

=== np_generated ===
                 task     condition metric     score
0   active_to_passive      baseline   bleu  0.259598
1   active_to_passive          np01   bleu  0.182392
2   active_to_passive          np05   bleu  0.182625
3   active_to_passive          np10   bleu  0.156554
4   active_to_passive  np_generated   bleu  0.151725
5   disambiguation_qa      baseline     em  0.000000
6   disambiguation_qa          np01     em  0.000000
7   disambiguation_qa          np05     em  0.000000
8   disambiguation_qa          np10     em  0.000000
9   disambiguation_qa  np_generated     em  0.000000
10     dyck_languages      baseline     em  0.000000
11     dyck_languages          np01     em  0.000000
12     dyck_languages          np05     em  0.000000
13     dyck_languages          np10     em  0.000000
14     dyck_languages  np_generated     em  0.000000
15           negation      baseline     em  0.000000
16           negation          np01     em  0.000000
17           negation          np05     em  0.000000
18           negation          np10     em  0.000000
19           negation  np_generated     em  0.000000
20    object_counting      baseline     em  0.000000
21    object_counting          np01     em  0.000000
22    object_counting          np05     em  0.000000
23    object_counting          np10     em  0.000000
24    object_counting  np_generated     em  0.000000
25         ruin_names      baseline   bleu  0.017173
26         ruin_names          np01   bleu  0.015019
27         ruin_names          np05   bleu  0.012944
28         ruin_names          np10   bleu  0.011327
29         ruin_names  np_generated   bleu  0.012110
30          sentiment      baseline     em  0.000000
31          sentiment          np01     em  0.000000
32          sentiment          np05     em  0.000000
33          sentiment          np10     em  0.000000
34          sentiment  np_generated     em  0.000000
35  translation_en-fr      baseline   bleu  0.007952
36  translation_en-fr          np01   bleu  0.005203
37  translation_en-fr          np05   bleu  0.005631
38  translation_en-fr          np10   bleu  0.004553
39  translation_en-fr  np_generated   bleu  0.004567
40    word_in_context      baseline     em  0.000000
41    word_in_context          np01     em  0.000000
42    word_in_context          np05     em  0.000000
43    word_in_context          np10     em  0.000000
44    word_in_context  np_generated     em  0.000000
45       word_sorting      baseline     em  0.000000
46       word_sorting          np01     em  0.000000
47       word_sorting          np05     em  0.000000
48       word_sorting          np10     em  0.000000
49       word_sorting  np_generated     em  0.000000

Saved to: results_final_np_llama2.csv

In [ ]:
import pandas as pd

df_llama2 = pd.read_csv("/kaggle/working/NegativePrompt/results_final_np_llama2.csv")
df_llama2.round(3)

                 task     condition metric  score
0   active_to_passive      baseline   bleu  0.260
1   active_to_passive          np01   bleu  0.182
2   active_to_passive          np05   bleu  0.183
3   active_to_passive          np10   bleu  0.157
4   active_to_passive  np_generated   bleu  0.152
5   disambiguation_qa      baseline     em  0.000
6   disambiguation_qa          np01     em  0.000
7   disambiguation_qa          np05     em  0.000
8   disambiguation_qa          np10     em  0.000
9   disambiguation_qa  np_generated     em  0.000
10     dyck_languages      baseline     em  0.000
11     dyck_languages          np01     em  0.000
12     dyck_languages          np05     em  0.000
13     dyck_languages          np10     em  0.000
14     dyck_languages  np_generated     em  0.000
15           negation      baseline     em  0.000
16           negation          np01     em  0.000
17           negation          np05     em  0.000
18           negation          np10     em  0.000
19           negation  np_generated     em  0.000
20    object_counting      baseline     em  0.000
21    object_counting          np01     em  0.000
22    object_counting          np05     em  0.000
23    object_counting          np10     em  0.000
24    object_counting  np_generated     em  0.000
25         ruin_names      baseline   bleu  0.017
26         ruin_names          np01   bleu  0.015
27         ruin_names          np05   bleu  0.013
28         ruin_names          np10   bleu  0.011
29         ruin_names  np_generated   bleu  0.012
30          sentiment      baseline     em  0.000
31          sentiment          np01     em  0.000
32          sentiment          np05     em  0.000
33          sentiment          np10     em  0.000
34          sentiment  np_generated     em  0.000
35  translation_en-fr      baseline   bleu  0.008
36  translation_en-fr          np01   bleu  0.005
37  translation_en-fr          np05   bleu  0.006
38  translation_en-fr          np10   bleu  0.005
39  translation_en-fr  np_generated   bleu  0.005
40    word_in_context      baseline     em  0.000
41    word_in_context          np01     em  0.000
42    word_in_context          np05     em  0.000
43    word_in_context          np10     em  0.000
44    word_in_context  np_generated     em  0.000
45       word_sorting      baseline     em  0.000
46       word_sorting          np01     em  0.000
47       word_sorting          np05     em  0.000
48       word_sorting          np10     em  0.000
49       word_sorting  np_generated     em  0.000

##### Test sur Vicuna-7B-v1.5

In [ ]:
!python eval_final_np_vicuna.py

config.json: 100%|█████████████████████████████| 615/615 [00:00<00:00, 3.30MB/s]
tokenizer_config.json: 100%|███████████████████| 749/749 [00:00<00:00, 3.42MB/s]
tokenizer.model: 100%|███████████████████████| 500k/500k [00:00<00:00, 2.03MB/s]
special_tokens_map.json: 100%|█████████████████| 438/438 [00:00<00:00, 2.22MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
pytorch_model.bin.index.json: 26.8kB [00:00, 15.0MB/s]
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Downloading (incomplete total...):   0%|            | 0.00/13.5G [00:00<?, ?B/s]

model.safetensors.index.json: 28.1kB [00:00, 37.2MB/s]A
Downloading (incomplete total...): 100%|████| 13.5G/13.5G [00:41<00:00, 421MB/s]
Fetching 2 files: 100%|███████████████████████████| 2/2 [00:41<00:00, 20.75s/it]
Download complete: 100%|████████████████████| 13.5G/13.5G [00:41<00:00, 325MB/s]
Loading weights: 100%|█| 291/291 [00:04<00:00, 71.04it/s, Materializing param=mo
generation_config.json: 100%|███████████████████| 162/162 [00:00<00:00, 958kB/s]
The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

=== baseline ===

=== np01 ===

=== np05 ===

=== np10 ===

=== np_generated ===
                 task     condition metric     score
0   active_to_passive      baseline   bleu  0.008121
1   active_to_passive          np01   bleu  0.005346
2   active_to_passive          np05   bleu  0.005640
3   active_to_passive          np10   bleu  0.004900
4   active_to_passive  np_generated   bleu  0.005150
5   disambiguation_qa      baseline     em  0.000000
6   disambiguation_qa          np01     em  0.000000
7   disambiguation_qa          np05     em  0.000000
8   disambiguation_qa          np10     em  0.000000
9   disambiguation_qa  np_generated     em  0.000000
10     dyck_languages      baseline     em  0.000000
11     dyck_languages          np01     em  0.000000
12     dyck_languages          np05     em  0.000000
13     dyck_languages          np10     em  0.000000
14     dyck_languages  np_generated     em  0.000000
15           negation      baseline     em  0.000000
16           negation          np01     em  0.000000
17           negation          np05     em  0.000000
18           negation          np10     em  0.000000
19           negation  np_generated     em  0.000000
20    object_counting      baseline     em  0.000000
21    object_counting          np01     em  0.000000
22    object_counting          np05     em  0.000000
23    object_counting          np10     em  0.000000
24    object_counting  np_generated     em  0.000000
25         ruin_names      baseline   bleu  0.005944
26         ruin_names          np01   bleu  0.003949
27         ruin_names          np05   bleu  0.002448
28         ruin_names          np10   bleu  0.002204
29         ruin_names  np_generated   bleu  0.002215
30          sentiment      baseline     em  0.000000
31          sentiment          np01     em  0.000000
32          sentiment          np05     em  0.000000
33          sentiment          np10     em  0.000000
34          sentiment  np_generated     em  0.000000
35  translation_en-fr      baseline   bleu  0.000000
36  translation_en-fr          np01   bleu  0.000000
37  translation_en-fr          np05   bleu  0.000000
38  translation_en-fr          np10   bleu  0.000000
39  translation_en-fr  np_generated   bleu  0.000000
40    word_in_context      baseline     em  0.000000
41    word_in_context          np01     em  0.000000
42    word_in_context          np05     em  0.000000
43    word_in_context          np10     em  0.000000
44    word_in_context  np_generated     em  0.000000
45       word_sorting      baseline     em  0.000000
46       word_sorting          np01     em  0.000000
47       word_sorting          np05     em  0.000000
48       word_sorting          np10     em  0.000000
49       word_sorting  np_generated     em  0.000000

Saved to: results_final_np_vicuna.csv

In [ ]:
import pandas as pd

df_vic = pd.read_csv("/kaggle/working/NegativePrompt/NegativePrompt/results_final_np_vicuna.csv")
df_vic.round(3)

                 task     condition metric  score
0   active_to_passive      baseline   bleu  0.008
1   active_to_passive          np01   bleu  0.005
2   active_to_passive          np05   bleu  0.006
3   active_to_passive          np10   bleu  0.005
4   active_to_passive  np_generated   bleu  0.005
5   disambiguation_qa      baseline     em  0.000
6   disambiguation_qa          np01     em  0.000
7   disambiguation_qa          np05     em  0.000
8   disambiguation_qa          np10     em  0.000
9   disambiguation_qa  np_generated     em  0.000
10     dyck_languages      baseline     em  0.000
11     dyck_languages          np01     em  0.000
12     dyck_languages          np05     em  0.000
13     dyck_languages          np10     em  0.000
14     dyck_languages  np_generated     em  0.000
15           negation      baseline     em  0.000
16           negation          np01     em  0.000
17           negation          np05     em  0.000
18           negation          np10     em  0.000
19           negation  np_generated     em  0.000
20    object_counting      baseline     em  0.000
21    object_counting          np01     em  0.000
22    object_counting          np05     em  0.000
23    object_counting          np10     em  0.000
24    object_counting  np_generated     em  0.000
25         ruin_names      baseline   bleu  0.006
26         ruin_names          np01   bleu  0.004
27         ruin_names          np05   bleu  0.002
28         ruin_names          np10   bleu  0.002
29         ruin_names  np_generated   bleu  0.002
30          sentiment      baseline     em  0.000
31          sentiment          np01     em  0.000
32          sentiment          np05     em  0.000
33          sentiment          np10     em  0.000
34          sentiment  np_generated     em  0.000
35  translation_en-fr      baseline   bleu  0.000
36  translation_en-fr          np01   bleu  0.000
37  translation_en-fr          np05   bleu  0.000
38  translation_en-fr          np10   bleu  0.000
39  translation_en-fr  np_generated   bleu  0.000
40    word_in_context      baseline     em  0.000
41    word_in_context          np01     em  0.000
42    word_in_context          np05     em  0.000
43    word_in_context          np10     em  0.000
44    word_in_context  np_generated     em  0.000
45       word_sorting      baseline     em  0.000
46       word_sorting          np01     em  0.000
47       word_sorting          np05     em  0.000
48       word_sorting          np10     em  0.000
49       word_sorting  np_generated     em  0.000

In [ ]:
!python eval_np_mistral.py

config.json: 100%|█████████████████████████████| 571/571 [00:00<00:00, 2.16MB/s]
tokenizer_config.json: 2.10kB [00:00, 4.71MB/s]
tokenizer.json: 1.80MB [00:00, 13.8MB/s]
tokenizer.model: 100%|████████████████████████| 493k/493k [00:00<00:00, 968kB/s]
special_tokens_map.json: 100%|█████████████████| 414/414 [00:00<00:00, 3.08MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors.index.json: 25.1kB [00:00, 47.7MB/s]
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Downloading (incomplete total...):  99%|███▉| 14.3G/14.5G [00:48<00:00, 411MB/s]
Fetching 2 files: 100%|███████████████████████████| 2/2 [00:48<00:00, 24.26s/it]
Download complete: 100%|████████████████████| 14.5G/14.5G [00:48<00:00, 298MB/s]
Loading weights: 100%|█| 291/291 [00:14<00:00, 20.10it/s, Materializing param=mo
generation_config.json: 100%|███████████████████| 116/116 [00:00<00:00, 377kB/s]

=== baseline ===

=== np01 ===

=== np05 ===

=== np10 ===
                 task condition metric     score
0   active_to_passive  baseline   bleu  1.000000
1   active_to_passive      np01   bleu  0.967995
2   active_to_passive      np05   bleu  1.000000
3   active_to_passive      np10   bleu  1.000000
4   disambiguation_qa  baseline     em  0.000000
5   disambiguation_qa      np01     em  0.000000
6   disambiguation_qa      np05     em  0.000000
7   disambiguation_qa      np10     em  0.000000
8      dyck_languages  baseline     em  0.400000
9      dyck_languages      np01     em  0.433333
10     dyck_languages      np05     em  0.300000
11     dyck_languages      np10     em  0.533333
12           negation  baseline     em  0.766667
13           negation      np01     em  0.766667
14           negation      np05     em  0.800000
15           negation      np10     em  0.766667
16    object_counting  baseline     em  0.366667
17    object_counting      np01     em  0.366667
18    object_counting      np05     em  0.266667
19    object_counting      np10     em  0.300000
20         ruin_names  baseline   bleu  0.118351
21         ruin_names      np01   bleu  0.132172
22         ruin_names      np05   bleu  0.100498
23         ruin_names      np10   bleu  0.123681
24          sentiment  baseline     em  0.833333
25          sentiment      np01     em  0.866667
26          sentiment      np05     em  0.833333
27          sentiment      np10     em  0.866667
28  translation_en-fr  baseline   bleu  0.136335
29  translation_en-fr      np01   bleu  0.123536
30  translation_en-fr      np05   bleu  0.129464
31  translation_en-fr      np10   bleu  0.117609
32    word_in_context  baseline     em  0.000000
33    word_in_context      np01     em  0.000000
34    word_in_context      np05     em  0.000000
35    word_in_context      np10     em  0.000000
36       word_sorting  baseline     em  0.333333
37       word_sorting      np01     em  0.266667
38       word_sorting      np05     em  0.166667
39       word_sorting      np10     em  0.300000

Saved to: results_mistral_baseline_np.csv